server {
  listen 8081;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Health check
  location = /health {
    add_header Content-Type text/plain;
    return 200 'ok';
  }

  # Static assets (important)
  location /assets/ {
    try_files $uri =404;
    expires 1y;
    access_log off;
  }

  # SPA fallback (THIS FIXES REFRESH 404)
  location / {
    try_files $uri $uri/ /index.html;
  }
}
